### ISSUE TITLE
Non unity c# version of the SDK?

### ISSUE THREAD

**Issue by ismyhc** [getbraincloud/braincloud-csharp#207]
Id like to use the SDK with Godot C#. Is there a version of the SDK that's not unity specific?

**Comment by ismyhc** [comment]
Nevermind. I think I figured it out :)

**Comment by davidstl** [comment]
Yes, if used outside of Unity, it will just be normal .NET. 
But I'm wondering if that will work in godot env, let us know!

**Comment by ismyhc** [comment]
Yeah I’m trying it now. Godot has a C# version. I have it all compiling so far will report back. 

I’d love to see a legit godot addon at some point. Godot is gaining a lot of traction!
