### ISSUE TITLE
Create new app: "error 400 bad request"

### ISSUE THREAD

**Issue by unitycoder** [getbraincloud/braincloud-csharp#222]
imported latest package to unity (2020.3.21f1), logged in, tried to create new app:
![image](https://user-images.githubusercontent.com/5438317/143015247-77d093cd-1ee7-4fff-8719-148a1300d03c.png)

**Comment by davidstl** [comment]
Hi, thanks for the report, we'll look into it

**Comment by unitycoder** [comment]
i think solved it, i was not admin on that team. (works if created new team for myself to test, as admin)
error message could show more info, if it was that issue why it failed.

thanks!

**Comment by davidstl** [comment]
Oh great to know. Ok we will create a ticket for a better error message there. Thanks for the suggestion
