### ISSUE TITLE
Unity Package Manager

### ISSUE THREAD

**Issue by docchang** [getbraincloud/braincloud-csharp#247]
Could you make the brain cloud git repo Package Manager(Unity) compatible?

**Comment by michaelc-bitheads** [comment]
Hello @docchang!

We now have brainCloud available as a custom package for Unity's package manager here:
- https://github.com/getbraincloud/braincloud-unity-package

Instructions here:
- https://github.com/getbraincloud/braincloud-csharp#package-manager

If you have any further questions, please feel free to reach out to us!

Cheers.
