### ISSUE TITLE
Readme is outdated for Unity

### ISSUE THREAD

**Issue by dylanh724** [getbraincloud/braincloud-csharp#261]
Where are the example scenes mentioned?
![image](https://github.com/getbraincloud/braincloud-csharp/assets/8840024/91103905-089a-4e95-b80a-a5202d9c752c)

**Comment by michaelc-bitheads** [comment]
Hello!

Yes, the README.md was definitely in need of an update. Luckily, we did just that for the latest release!

While there is a Unity project in this GitHub it has mostly been relegated for Unit Testing. The best way to get started with Unity now is to either [download the latest .unitypackage](https://github.com/getbraincloud/braincloud-csharp/releases/tag/5.1.0/) or add the plugin via Unity's [Package Manager](https://github.com/getbraincloud/braincloud-unity-package/#braincloud-unity-custom-package).

There is some example code in the README for [initializing brainCloud through the BrainCloudWrapper](https://github.com/getbraincloud/braincloud-csharp#how-do-i-initialize-braincloud), but the best way to learn is to check out our [examples](https://github.com/getbraincloud/examples-unity/)! Our [Authentication example](https://github.com/getbraincloud/examples-unity/tree/master/Authentication/) is a great place to start with brainCloud in my humble opinion ;)

Let us know if you have any further questions!

Cheers,
-Michael Costa
